# Generated by Django 3.1.7 on 2021-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_issue',
            field=models.CharField(max_length=30, verbose_name='Тип'),
        ),
    ]
