# Generated by Django 3.1.7 on 2021-03-14 10:19

from django.db import migrations


def types_transfer(apps, schema_editor):
    Issue = apps.get_model('tracker.Issue')
    for issue in Issue.objects.all():
        issue.types.set([issue.type_issue])


def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('tracker.Issue')
    for issue in Issue.objects.all():
        issue.type_issue = issue.types.first()
        issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210314_1014'),
    ]

    operations = [migrations.RunPython(types_transfer, rollback_transfer)
    ]
