# Generated by Django 3.1.7 on 2021-03-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_data_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type_issue',
        ),
    ]
