# Generated by Django 3.1.7 on 2021-03-18 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_issue_type_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[django.core.validators.MaxLengthValidator(3000), django.core.validators.MinLengthValidator(6)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300), django.core.validators.MinLengthValidator(6)], verbose_name='Заголовок'),
        ),
    ]
