# Generated by Django 3.1.7 on 2021-03-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20210330_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_deleted',
        ),
    ]
