# Generated by Django 3.1.7 on 2021-04-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20210414_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('project_user_update', 'Can update users in project')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
