# Generated by Django 3.1.7 on 2021-04-16 15:50

from django.db import migrations


def create_profiles(app, schema_editor):
    User = app.get_model('auth', 'User')
    Profile = app.get_model('accounts', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop)
    ]
